name: tests

on:
  push:
    branches:
      - main
    paths:
      - "src/test/java/**"
  repository_dispatch:
    types: [run-tests]

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: Archive Reports Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: TestReports
          path: target/TestReports
          retention-days: 1
